### ISSUE TITLE
Add tick in Header on android on SavePaletteScreen 

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma#116]
Refactor code to move SavePalette component in the screen itself and get rid of AddPaletteManuallyScreen after extending the functionality of SavePaletteScreen.
![Screenshot from 2020-10-25 09-53-11](https://user-images.githubusercontent.com/5221843/97098861-ef980900-16a7-11eb-804d-c05bcb28a8ce.png)

Refer to ColorListScreen for a similar example

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?
