### ISSUE TITLE
internationalization support 

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma#119]
Find out how to do this in react native and implement it for the following items
* Buttons 
* Header titles
* description 
* side menu items
* helper text

**Comment by shachargiladi** [comment]
hey, is this issue still relevant? if so, can you give more specific details?

**Comment by kamalkishor1991** [comment]
Hi @shachargiladi, yes this is still relevent. Thanks for checking it.
You can take this as a referance. 
https://www.reactnative.guide/13-internationalization/13.1-framework-intro.html
Basically all the text that is visiable to user should have localized entry in some kind of config file like en.json, hi.json etc.

**Comment by ebiroud** [comment]
Hi, if this issue isn't being worked on, could you assign me to it? Thank you!

**Comment by kamalkishor1991** [comment]
@ebiroud assigned. Thanks a lot.

**Comment by kamalkishor1991** [comment]
@ebiroud thanks a lot for implementing this.
