### ISSUE TITLE
Add ability to order colors inside palatte 

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma#154]
Suggestion from review - 
" could have the option to reorganize the order of the colors in a palette, so we can more easily check color interactions"
<img width="1033" alt="Screenshot 2022-10-02 at 7 48 08 AM" src="https://user-images.githubusercontent.com/5221843/193435020-d32df04a-61db-4b91-b0f2-24ec3b30c6ec.png">

**Comment by Walia8416** [comment]
Please assign this issue to me

**Comment by kamalkishor1991** [comment]
Assigned. Thanks @Walia8416 for picking this up. Please let me know if you need any help or clearification with this?

**Comment by Walia8416** [comment]
#158 this issue has been solved please review @kamalkishor1991

**Comment by Walia8416** [comment]
I have created a pr for this issue please assign and close this issue along with the [hacktoberfest-accepted](https://github.com/sukritishah15/DS-Algo-Point/issues?q=is%3Aopen+label%3Ahacktoberfest-accepted) tag @kamalkishor1991

**Comment by kamalkishor1991** [comment]
Already implemented now with #171
