### ISSUE TITLE
Move "add new palette manually" to main button 

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma#155]
Adding new palette manually seems to be more useful feature. We can remove scan colors from the action button and move add new palette to it.

**Comment by stellarleo** [comment]
Hello, I would like to try and solve this issue!

**Comment by Walia8416** [comment]
I have completed this for hacktoberfest 2022

**Comment by Walia8416** [comment]
I have created a pr for this issue please assign and close this issue along with the [hacktoberfest-accepted](https://github.com/sukritishah15/DS-Algo-Point/issues?q=is%3Aopen+label%3Ahacktoberfest-accepted) tag

**Comment by Walia8416** [comment]
@kamalkishor1991

**Comment by kamalkishor1991** [comment]
Thanks @Walia8416, closing the issue now.
