### ISSUE TITLE
Add option to export color palette to PNG 

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma#156]
Based on a review on playstore.

<img width="1033" alt="Screenshot 2022-10-02 at 7 48 08 AM" src="https://user-images.githubusercontent.com/5221843/193444825-ab5cb68d-c5ac-40f9-ad35-08d9bf59225c.png">

**Comment by zadzora** [comment]
Hi, i would like take a look on this issue/feature. Can you asign this to me ?

**Comment by kamalkishor1991** [comment]
@zadzora Assigned. thanks for checking it. Please let me know if you need any help. 
Discord channel: https://discord.com/invite/ZSBVsBqDtg

**Comment by kamalkishor1991** [comment]
Done for android now. #170 
We need to figure out iOS download notification and test the functionality in iOS.

**Comment by kamalkishor1991** [comment]
#173 Done for iOS also.
