### ISSUE TITLE
Navigation Menu overlapping on Web Mobile

### ISSUE THREAD

**Issue by highb33kay** [croma-app/croma#160]
Issue: the navigation Menu Discord overlaps the edit button on mobile. 

OS: Android. 

![Screenshot_20221016-091212](https://user-images.githubusercontent.com/89009222/196025513-37a4d5dc-b8b0-40eb-8d74-0cbde695867d.png)

**Comment by kamalkishor1991** [comment]
Thanks @highb33kay for reporting. We need to only show 3 icons in the home screen and not show these icons in other screens. Please feel free to fix it if anyone is interested. This needs to be fixed in the web branch.

**Comment by highb33kay** [comment]
Assign me then. Thank you @kamalkishor1991

**Comment by highb33kay** [comment]
Can you point me in the right direction as to location the code source?

**Comment by highb33kay** [comment]
I think I see it [Navigation](https://github.com/croma-app/croma/blob/web/navigation/NavigatorHelper.js)

**Comment by kamalkishor1991** [comment]
Yes it is defined here
https://github.com/croma-app/croma/blob/51f1793c20597d1463a4fb4314f25fb8bcc69d1d/navigation/NavigatorHelper.js#L161

**Comment by highb33kay** [comment]
Hi again @kamalkishor1991 . I don't know enough react to fix this alone. So any suggestions?

So here is what I have so far:
1. I think the navigationHelper.js file is okay and the issue lies in the different screen the function is being called. A sure fix would be to remove any screen that isnt the home screen that calls this function.
2. If 1 is not the case, another theory is that the navigation menus somehow got tangled together and are being bundled as one, which is causing the issue. a fix would be to untangle them (Sorry if i am not using the right words, I dont really understand how react works) 

That is all I have as far as theories are concerned. 

I tried using chrome inspect tools and I found out that doesn't work for react lol.

**Comment by kamalkishor1991** [comment]
@highb33kay 
I think way to implement it is to remove it from navigation and implement a custom header. You can refer to custom header here.
https://github.com/croma-app/croma/blob/51f1793c20597d1463a4fb4314f25fb8bcc69d1d/screens/ColorListScreen.js#L53

**Comment by highb33kay** [comment]
That is a big help, thank you.

**Comment by nisilachandunu** [comment]
is this issue fixed?

**Comment by kamalkishor1991** [comment]
@nisilachandunu no.

**Comment by willdelorm** [comment]
Hi @kamalkishor1991, I'd like to take a stab at this. Is that alright? :)

**Comment by kamalkishor1991** [comment]
@willdelorm sure. Thanks
Let me know if you need any help

**Comment by mtalhabaig3** [comment]
Hi @kamalkishor1991, I'd like to try to fix this issue, will that be alright?
