### ISSUE TITLE
On mobile browser the scrollview children are getting pressed while scrolling

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma#17]
* open http://croma.app on mobile browser.
* scroll any view multiple times.
* onPress will happen while scrolling

**Comment by kamalkishor1991** [comment]
@satya164 any idea why this might be happening? I tried searching in multiple places but not able to get any hint?

**Comment by kamalkishor1991** [comment]
https://github.com/necolas/react-native-web/issues/1219
Added a workaround mentioned on the above issue. Keeping it open until the above issue is fixed.

**Comment by bhujoshi** [comment]
@kamalkishor1991 after workaround fix clicking on the delete icon doing 2 actions open palette and delete the palette
