### ISSUE TITLE
Sometimes loading spinner never stop loading when trying to extract color from image.

### ISSUE THREAD

**Issue by bhujoshi** [croma-app/croma#94]
**Steps to reproduce**

1. Open the Croma app on android.
2. Pick colors using **Get a palette from images** 
3. Come back to the home screen and minimize the app.
4. Then open it again from the background 
5. Select pick image using **Get a palette from the image** and the loader never stops loading.

**Expected behavior**
It should always display save palette screen after selecting the image.

**Comment by kamalkishor1991** [comment]
This should no longer be the case after rewrite and upgrading to react. Please reopen if the issue is still present.
